### ISSUE TITLE
small white-outlined box in upper left

### ISSUE THREAD

**Issue by rittwage** [mist-devel/c64#10]
A small white-outlined box in upper left part of the screen appears when mounting certain CRT images, and does not disappear.

For example: hero.crt

**Comment by gyurco** [comment]
It turns on the datasette motor for some reason. If it bothers you, then turn off the tape progressbar in the OSD.

**Comment by rittwage** [comment]
Thanks!

I guess because cartridges sometimes much around with address $01?

**Comment by gyurco** [comment]
And probably they don't care about the motor bit.
