### ISSUE TITLE
Feature Request: remap keyboard

### ISSUE THREAD

**Issue by mvdhoning** [mist-devel/c64#16]
Can it be possible to remap keys?
E.g. remap restore to pgdn or \?

I use a 68key (65%) keyboard. And with that i have to use fn with number key to use funtion keys.
Also the back arrow is under the escape key when use fn.
But in practice this means i cannot do runstop restore. As to do F11 (restore) i have to use fn but then escape (run stop) becomes back arrow.

i asume escape is runstop but i am not certain as that is not listed in the doc where i downloaded the fpga64 core.

only keys with no mapping are del (end) and pgdn.

sidenote doing ctrl =+ key makes a freeze. is that also mapped to something special?

**Comment by sorgelig** [comment]
You can remap keys in "Button/Key remap".
In general reduced keyboards aren't good choice for MiSTer because retro computers occupy almost all keys of base PC keyboard and some additional functions require extended keys.

**Comment by mvdhoning** [comment]
Help me a little with "Button/Key remap" where do i find that?

**Comment by mvdhoning** [comment]
went hunting in the sources for the firmware regarding the mist.ini and found key_remap.
with some experimenting i discovered that it needs ps2 keycodes and the first is the key you want to bind a value to and the second is the key that it has to become.
key_remap=31,44
key_remap=4C,31
so for now i changed \ to F11 and END to \ 
also somewhat mimics the prints on my china budget c64 look alike keycaps.
but with this working i feel there is no more need for this feature request. so i close it.
what could be a request but not for here is more documentation on the mist.ini or more documentation in general.

**Comment by harbaum** [comment]
Documentation is fortunately something where most people can contribute.

**Comment by sorgelig** [comment]
Sorry about my comment. I've got several new issues about C64 core and didn't see this one is in MiST repo.
