### ISSUE TITLE
Tape sound

### ISSUE THREAD

**Issue by Maverick-Shark** [mist-devel/c64#18]
Poseidon board: Enabling 'Tape Sound ON' from OSD, it doesn't work.  No tape sound is heard.

Please, could you check it on MiST if it sounds?

Thanks and best regards,
Shark

**Comment by gyurco** [comment]
What's the source? The internal TAP player or the external audio input?

**Comment by Maverick-Shark** [comment]
Internal TAP player.

**Comment by Maverick-Shark** [comment]
Awesome!! Now it's working!!! <;-) <;-) <;-)

Thanks a lot for your work,
Shark
