### ISSUE TITLE
1351 Mouse does not work in FC3

### ISSUE THREAD

**Issue by egrath** [mist-devel/c64#5]
Hi, the 1351 Mouse does work in almost any applications i've tried - including the famous mousetest2 - but for some reason not in Final Cartridge III. On a real C64 this works, also under Emulation with VICE.

I attached the CRT of FC3 which works in Vice and also a D64 Image of mousetest2.

[Final_Cartridge_3_Plus_2015-09_V4.1.zip](https://github.com/mist-devel/c64/files/9331421/Final_Cartridge_3_Plus_2015-09_V4.1.zip)
[mousetest2.zip](https://github.com/mist-devel/c64/files/9331438/mousetest2.zip)

**Comment by sorgelig** [comment]
strange.. i will check

**Comment by sorgelig** [comment]
just tried your FC3 cart - mouse works fine. Check other OSD options - may be something prevents mouse to work in FC3.

**Comment by gyurco** [comment]
Did you try it on MiST? :)

BTW, seems the mouse detection depends on the LSB bit is being 'noise'. So if you shake the mouse when you load the cart, it'll be detected.

**Comment by egrath** [comment]
I can confirm the behavior @gyurco mentioned. Just tried many different FC3 CRTs and all with 1351 support work when the mouse is moved during load. I'm using FW ATH220805 and FPGA64 220530. Any chance of getting this fixed in any of the next releases?

**Comment by gyurco** [comment]
Here's a compiled core if you want to test.
[C64_mist.zip](https://github.com/mist-devel/c64/files/9333820/C64_mist.zip)

**Comment by sorgelig** [comment]
oops... i'm really sorry, didn't notice it's in MiST version :)

**Comment by egrath** [comment]
Can confirm that the new core binary works as expected with different versions of FC3. Thank you very much for the fix!
