### ISSUE TITLE
Backport Dolphin DOS parallel cable support from MiSTer

### ISSUE THREAD

**Issue by egrath** [mist-devel/c64#7]
Would it be possible to backport the parallel cable and ram extension from MiSTer's 1541 implementation to the MiST? This would speed up disk loading for people who don't own JiffyDOS as their kernal/drive rom replacement significantly.

**Comment by Julitium** [comment]
Hi.
Perhaps you can achieve this by making a rom file and substituting the appropriate images.
All the best.

**Comment by egrath** [comment]
My intent is to use DolphinDOS as the Kernal for the C64 and the 1541. For performance reasons, DolphinDOS used a parallel cable between the userport and the 1541. JiffyDOS is slightly slower and in addition is not freely available - but it does not need a cable and currently works as expected in FPGA64. Fastloaders like the FC3 cartridge only accelerated the load of the first PRG from disk, not subsequent loads, so they are more like a workaround and were previously used mostly by C64 owners who didn't wanted to solder in new ROMS.

**Comment by gyurco** [comment]
I checked the schematics of Dolphin DOS 3.0 expansion, if the 8K RAM extension fits, then it's doable.

**Comment by Julitium** [comment]
Hi.
There was also an 8K upgrade called RAMBOard. Although there is very little software that takes advantage of it, it may be easy to add it.
all the best

**Comment by egrath** [comment]
To document the potential performance gains which would occur if implemented i attached some screenshots comparing the various methods currently available.

**Stock configuration**
![speed_stock](https://user-images.githubusercontent.com/1955895/185767770-43f0a2b5-f2da-4974-9587-8090e22e03ef.png)

**JiffyDOS 6.01 (kernal/drive roms), currently possible on FPGA64**
![speed_jiffy601](https://user-images.githubusercontent.com/1955895/185767627-b2553e46-e26e-4b9e-b1b5-a3758fd61077.png)

**Action Replay 6 (stock kernal/1541; cartridge attached), currently possible on FPGA64**
![speed_actionreplay6](https://user-images.githubusercontent.com/1955895/185767651-df4c4125-4159-46d3-9bf0-d608887d0180.png)

**DolphinDOS 2.0 (kernal/drive roms and parallel cable), currently NOT possible**
![speed_dolphin2](https://user-images.githubusercontent.com/1955895/185767660-63b154c7-ed58-4cba-bc64-c575a8821ce7.png)

Clearly, DolphinDOS excels in every category and makes disk access a breeze. The program used was the 64er Magazine Speed-Test:
[speed-test.zip](https://github.com/mist-devel/c64/files/9388062/speed-test.zip)

**Comment by gyurco** [comment]
I took a closer look at this, and unfortunately the 1541 ROM also expanded to 32K (Dolphin DOS uses 24K only). That means this addition would require +14K more BRAM, which is very close to what's available.

**Comment by egrath** [comment]
Even if it might fit, it's probably better to not implement it, as this would leave to little free LUs for potentially needed future bugfixes and more urgently needed additions.
