### ISSUE TITLE
Specify default cartridge?

### ISSUE THREAD

**Issue by egrath** [mist-devel/c64#8]
Hello, is it currently possible to specify a default cartridge to load on core startup (like by giving the CRT file a special name). If not, would it be eventually possible to include such a feature in a future release. 
Cheers, egrath

**Comment by gyurco** [comment]
It's possible, but it would be a new firmware feature, the core doesn't have to be involved.
Maybe automatically loading <corename>.RXX for the various indices could be added.

**Comment by egrath** [comment]
Ah OK, thanks for the info, that really would be a nice feature for many systems which support cartridges. Should i open a new Issue in the mist-firmware repository or can you move the ticket over?

**Comment by gyurco** [comment]
You can leave it here, there are no thousands of tickets to handle :)

**Comment by gyurco** [comment]
C64.R02 can be a default CRT image.

**Comment by egrath** [comment]
I just tried this feature with the latest firmware (221122) and the test core you supplied in https://github.com/mist-devel/c64/issues/9, but can't get the any CRT to autoload. Placed the CRT as "C64.R02" on the root of the SD card but it don't gets loaded. On the card i have:

```
MIST.INI
CORE.RBF
C64.ROM
C64.R02
C64.CFG
```

**Comment by gyurco** [comment]
Sorry, there was a bug. Try the attached core.
[C64_230227.zip](https://github.com/mist-devel/c64/files/10843461/C64_230227.zip)

**Comment by egrath** [comment]
Thank you! Yes this version works as intended! Just loaded RR 3.8Q renamed to C64.R02 and put it next to the RBF and ROM and it automatically loads at startup.
